version: '3'

services:
  back-end:
    build:
      context: ./back-end
      target: ci
    environment:
      TEST_DATABASE_URL: postgres://postgres:password@test-database:5432/postgres
    depends_on:
      - test-database

  test-database:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_PASSWORD: password
    expose:
      - 5432
